### ISSUE TITLE
錯誤訊息洗頻

### ISSUE THREAD

**Issue by changchiyou** [changchiyou/haplog#2]
如果運行到一半的專案出問題了，`haplog`不會關掉，反而會無限循環噴錯（這邊拿某個 private repo 開發到一半遇到的錯誤來示範）：

```
...
2023-06-17 19:20:12,219 DEBUG    [facepcs] realtime_recognition.py - loop() : start
Traceback (most recent call last):
  File "/Users/christopherchang/miniconda3/envs/facepcs/bin/facepcs-cli", line 33, in <module>
    sys.exit(load_entry_point('facepcs', 'console_scripts', 'facepcs-cli')())
  File "/Users/christopherchang/Work/FacePCS/python-package/facepcs/commands/facepcs_cli.py", line 40, in main
    service.run()
  File "/Users/christopherchang/Work/FacePCS/python-package/facepcs/commands/realtime.py", line 205, in run
    realtime()
  File "/Users/christopherchang/Work/FacePCS/python-package/facepcs/app/realtime_recognition.py", line 303, in realtime
    realtime_recognition.loop()
  File "/Users/christopherchang/Work/FacePCS/python-package/facepcs/app/realtime_recognition.py", line 117, in loop
    if np.ndarray((pre_frame == frame)).all():
ValueError: maximum supported dimension for an ndarray is 32, found 720
Oops! An issue occurred during the logging process:
Traceback (most recent call last):
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/site-packages/haplog/logger_utils.py", line 160, in listener_process
    record = _queue.get()
  File "<string>", line 2, in get
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
    kind, result = conn.recv()
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Oops! An issue occurred during the logging process:
Traceback (most recent call last):
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/site-packages/haplog/logger_utils.py", line 160, in listener_process
    record = _queue.get()
  File "<string>", line 2, in get
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

後面就是無限迴圈：

```
Oops! An issue occurred during the logging process:
Traceback (most recent call last):
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/site-packages/haplog/logger_utils.py", line 160, in listener_process
    record = _queue.get()
  File "<string>", line 2, in get
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by changchiyou** [comment]
看起來很明顯是卡在這邊：

https://github.com/changchiyou/haplog/blob/2c84dc843cc57587c7525fb2e6fe74c6d06c7775/haplog/logger_utils.py#L165-L173

應該直接用：

https://github.com/changchiyou/haplog/blob/2c84dc843cc57587c7525fb2e6fe74c6d06c7775/haplog/logger_utils.py#L178-L180

將原先的 code 改成應該就可以解決問題了：

```
except BrokenPipeError:
     self.join()
except Exception: 
     import sys 
     import traceback 
  
     print( 
         "Oops! An issue occurred during the logging process:", 
         file=sys.stderr, 
     ) 
     traceback.print_exc(file=sys.stderr) 
```

**Comment by changchiyou** [comment]
重現錯誤、並確認不再會無限噴錯誤訊息：
```
2023-06-17 20:28:51,998 DEBUG    [facepcs] realtime_recognition.py - loop() : start
Traceback (most recent call last):
  File "/Users/christopherchang/miniconda3/envs/facepcs/bin/facepcs-cli", line 33, in <module>
    sys.exit(load_entry_point('facepcs', 'console_scripts', 'facepcs-cli')())
  File "/Users/christopherchang/Work/FacePCS/python-package/facepcs/commands/facepcs_cli.py", line 40, in main
    service.run()
  File "/Users/christopherchang/Work/FacePCS/python-package/facepcs/commands/realtime.py", line 205, in run
    realtime()
  File "/Users/christopherchang/Work/FacePCS/python-package/facepcs/app/realtime_recognition.py", line 298, in realtime
    realtime_recognition.loop()
  File "/Users/christopherchang/Work/FacePCS/python-package/facepcs/app/realtime_recognition.py", line 112, in loop
    if np.ndarray((pre_frame == frame)).all():
ValueError: maximum supported dimension for an ndarray is 32, found 720
Oops! An issue occurred during the logging process:
Traceback (most recent call last):
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/site-packages/haplog/logger_utils.py", line 160, in listener_process
    record = _queue.get()
  File "<string>", line 2, in get
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
    kind, result = conn.recv()
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process Process-2:
Traceback (most recent call last):
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/site-packages/haplog/logger_utils.py", line 160, in listener_process
    record = _queue.get()
  File "<string>", line 2, in get
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/site-packages/haplog/logger_utils.py", line 167, in listener_process
    self.join()
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/site-packages/haplog/logger_utils.py", line 182, in join
    self.queue.put_nowait(None)
  File "<string>", line 2, in put_nowait
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/Users/christopherchang/miniconda3/envs/facepcs/lib/python3.10/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```
